version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - app_net
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
